security.basic.enabled: false
multipart.maxFileSize: 3Mb

ecomm:
    resource:
        url: http://localhost:80/ecomm-resource/
        directory: C:\wamp\www\ecomm-resource\ #C:\Users\Administrator\Desktop\ecomm-resource\

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ecomm?useUnicode=true&characterEncoding=utf8
        username: root
        password: 
        max-active: 100
        max-idle: 8
        min-idle: 8
        initial-size: 10
        validation-query: select 1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 30000
        min-evictable-idle-time-millis: 20
        max-wait: 60000
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# logging:
#     level:
#         org.springframework.security: DEBUG
